
name: Pages

on:
  workflow_run:
    workflows: ["DotNet"]
    branches: [main]
    types: 
      - completed


jobs:
  # Build job
  build:
    # At a minimum this job should upload artifacts using actions/upload-pages-artifact

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100'

      - name: Restore Tools
        run: dotnet tool restore

      - name: Paket Restore
        run: dotnet paket restore

      - name: Build
        run: dotnet fable src --outDir bin/Build

      - name: Move HTML
        run: cp src/sources/index.html bin/Build/index.html

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action